$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@network1 = '192.168.64'
@network2 = '192.168.65'
@network3 = '192.168.66'

@hosts=Hosts.new('puppet.tst')
@hosts.add('aio', [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'aio' do |vm|
    host = 'aio'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder './', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end
    vm.vm.provision 'shell', path: common + 'repos/delorean.sh'
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'git_src.sh'
      s.args = [ 'openstacklib', 'https://github.com/stackforge/puppet-openstacklib.git', 'master', '/usr/share/openstack-puppet/modules' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'git_src.sh'
      s.args = [ 'keystone', 'https://github.com/stackforge/puppet-keystone.git', 'master', '/usr/share/openstack-puppet/modules' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'puppet_no_master.sh'
      s.args = [ '/usr/share/openstack-puppet/modules' ]
    end
  end
end
