$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

fatal ('Unsupported platform') unless PLATFORMS.include?(platform)

@network1 = '192.168.50'
@network2 = '192.168.51'
@network3 = '192.168.52'

@hosts=Hosts.new('os.tst')
@hosts.add('nha', [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'nha' do |vm|
    host = 'nha'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder './', '/vagrant', :rsync => true
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell', path: common + 'masterless.sh'
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @network1, @network2, @network3 ]
    end
  end
end
