$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@network1 = '192.168.48'
@network2 = '192.168.49'
@network3 = '192.168.50'

@hosts=Hosts.new('os.tst')
@hosts.add('pack1', [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'pack1' do |vm|
    host = 'pack1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6122
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = 'packstack_install.sh'
      s.args = [ @hosts.get(host)[0] ]
    end
  end
end

