$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.48'
@ipv4_net2 = '192.168.491'
@ipv4_net3 = '192.168.50'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('packstack.tst')
@hosts.add('pack1', ip: [ "#{@ipv4_net1}.11", "#{@ipv4_net2}.11", "#{@ipv4_net3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'pack1' do |vm|
    host = 'pack1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6122
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"

    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    if platform =~ /rhel7/
      vm.vm.provision 'shell' do |s|
        s.path = common + 'repos/rhel7.sh'
      end
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = 'packstack_install.sh'
      s.args = [ @hosts.get(host).name ]
    end
  end
end
