$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.160'
@ipv4_net2 = '192.168.161'
@ipv4_net3 = '192.168.162'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('xyz.tst')
@hosts.add('ospd1', ip: [ "#{@ipv4_net1}.10", "#{@ipv4_net2}.10", "#{@ipv4_net3}.10" ], ipv6: ["#{@ipv6_net1}::4"])

Vagrant.configure('2') do |config|
  config.vm.define 'one' do |vm|
    host = 'ospd1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"

    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'director.sh'
    end
  end
end
