$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.81'
@ipv4_net2 = '192.168.82'
@ipv4_net3 = '192.168.83'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('os.tst')
@hosts.add('controller1', ip: ["#{@ipv4_net1}.11", "#{@ipv4_net2}.11", "#{@ipv4_net3}.11"])
@hosts.add('controller2', ip: ["#{@ipv4_net1}.12", "#{@ipv4_net2}.12", "#{@ipv4_net3}.12"])
@hosts.add('controller3', ip: ["#{@ipv4_net1}.13", "#{@ipv4_net2}.13", "#{@ipv4_net3}.13"])
@hosts.add('compute1',    ip: ["#{@ipv4_net1}.30", "#{@ipv4_net2}.30", "#{@ipv4_net3}.30"])

if ansible?
  File.open('./inventory','w+') do |file|
    file << @hosts.ansible_inventory
  end
end

Vagrant.configure('2') do |config|
  config.vm.define 'controller1' do |vm|
    host = 'controller1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.volume_cache = 'none'
    end

    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + "quickstack.sh"
      s.args = [quickstack, quickstack_branch]
    end
    # vm.vm.provision 'shell', path: common + 'certificates.sh'
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
  end

  config.vm.define 'controller2' do |vm|
    host = 'controller2'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + "quickstack.sh"
      s.args = [ quickstack, quickstack_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
  end

  config.vm.define 'controller3' do |vm|
    host = 'controller3'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + "quickstack.sh"
      s.args = [quickstack, quickstack_branch]
    end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
  end

  config.vm.define 'compute1' do |vm|
    host = 'compute1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + "quickstack.sh"
      s.args = [quickstack, quickstack_branch]
    end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
  end
end
