$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

fatal ('Unsupported platform') unless PLATFORMS.include?(platform)

@network1 = '192.168.60'
@network2 = '192.168.61'
@network3 = '192.168.62'

@hosts=Hosts.new('os.tst')
@hosts.add('controller1', [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])
@hosts.add('compute1',    [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])
@hosts.add('compute2',    [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'controller1' do |vm|
    host = 'controller1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 4096
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end    
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = 'packstack_install.sh'
      s.args = [ '192.168.60.11' ]
    end
  end

  config.vm.define 'compute1' do |vm|
    host = 'compute1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end    
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
  end

  config.vm.define 'compute2' do |vm|
    host = 'compute2'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end    
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
  end
end
