$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.154'
@ipv4_net2 = '192.168.155'
@ipv4_net3 = '192.168.156'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('beaker.tst')
@hosts.add('test1', ip: [ "#{@ipv4_net1}.11", "#{@ipv4_net2}.11", "#{@ipv4_net3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'test1' do |vm|
    host = 'test1'
    vm.vm.box = 'centos7-dev'
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"

    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision "shell", path: common + 'beaker-deps.sh'

    vm.vm.provision "shell", path: common + 'beaker-ssh.sh', privileged: false

    vm.vm.provision 'shell' do |s|
      s.path = common + 'beaker-upgrade.sh'
      s.args = [ 'keystone', '98/213598/1', 'centos7', 'stable/kilo' ]
      s.privileged = false
    end
  end
end
