$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.51'
@ipv4_net2 = '192.168.52'
@ipv4_net3 = '192.168.53'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('packstack.tst')
@hosts.add('controller1', ip: [ "#{@ipv4_net1}.11", "#{@ipv4_net2}.11", "#{@ipv4_net3}.11" ])
@hosts.add('compute1', ip: [ "#{@ipv4_net1}.12", "#{@ipv4_net2}.12", "#{@ipv4_net3}.12" ])

Vagrant.configure('2') do |config|
  config.vm.define 'controller1' do |vm|
    host = 'controller1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 4096
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
    vm.vm.provision 'shell', inline: 'packstack --answer-file=/vagrant/answer.cfg'
  end

  config.vm.define 'compute1' do |vm|
    host = 'compute1'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
    end

    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, flea.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'packstack_dist.sh'
      s.args = [ 'rpm' ]
    end
  end
end
