$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@network1 = '192.168.40'
@network2 = '192.168.41'
@network3 = '192.168.42'

@hosts=Hosts.new('os.tst')
@hosts.add('aio', [ "#{@network1}.11", "#{@network2}.11", "#{@network3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'aio' do |vm|
    host = 'aio'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'quickstack.sh'
      s.args = [ quickstack, quickstack_branch ]
    end
    # vm.vm.provision 'shell', path: common + 'certificates.sh'
    #vm.vm.provision 'shell', path: common + "puppetmaster.sh"
    #vm.vm.provision 'shell' do |s|
    #  s.path = common + 'puppetdb.sh'
    #  s.args = [ host.to_s ]
    #end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @network1, @network2, @network3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
    vm.vm.provision 'shell', path: common + 'clean-hiera-aio.sh'
  end
end
