$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.40'
@ipv4_net2 = '192.168.41'
@ipv4_net3 = '192.168.42'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('os.tst')
@hosts.add('aio', ip: [ "#{@ipv4_net1}.11", "#{@ipv4_net2}.11", "#{@ipv4_net3}.11" ])

Vagrant.configure('2') do |config|
  config.vm.define 'aio' do |vm|
    host = 'aio'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'quickstack.sh'
      s.args = [ quickstack, quickstack_branch ]
    end
    # vm.vm.provision 'shell', path: common + 'certificates.sh'
    #vm.vm.provision 'shell', path: common + "puppetmaster.sh"
    #vm.vm.provision 'shell' do |s|
    #  s.path = common + 'puppetdb.sh'
    #  s.args = [ host.to_s ]
    #end
    vm.vm.provision 'shell' do |s|
      s.path = './hiera_custom.sh'
      s.args = [ @ipv4_net1, @ipv4_net2, @ipv4_net3 ]
    end
    vm.vm.provision 'shell', path: common + 'puppet_no_master.sh'
    vm.vm.provision 'shell', path: common + 'clean-hiera-aio.sh'
  end
end
