$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@network1 = '192.168.96'
@network2 = '192.168.97'
@network3 = '192.168.98'
@network4 = '192.168.99'

@hosts=Hosts.new('playstack.tst')
@hosts.add('aio', [ "#{@network1}.10", "#{@network2}.10", "#{@network3}.10", "#{@network4}.10" ])

Vagrant.configure('2') do |config|
  config.vm.define 'aio' do |vm|
    host = 'aio'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).each do |ip|
      vm.vm.network :private_network, :ip => ip
    end
    vm.vm.hostname = @hosts.fqdn(host)
    vm.vm.provision 'shell' do |s|
      s.path = common + 'pre.sh'
      s.args = [ @hosts.to_s ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end
#    vm.vm.provision 'shell', path: common + 'certificates.sh'
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell', path: common + 'selinux_off.sh'
    vm.vm.provision 'shell' do |s|
      s.path = common + 'puppet_no_master.sh'
      s.args = [ '/usr/share/openstack-puppet/modules' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'playstack.sh'
      s.args = [ 'master', @hosts.get(host)[0], @hosts.get(host)[1], @hosts.get(host)[2], 'true' ]
    end
  end
end
