$LOAD_PATH << ENV['VAGRANT_LIB']

require 'helpers'

@ipv4_net1 = '192.168.96'
@ipv4_net2 = '192.168.97'
@ipv4_net3 = '192.168.98'
@ipv4_net4 = '192.168.99'
@ipv4_default_gw = '192.168.121.1'

@hosts=Hosts.new('playstack.tst')
@hosts.add('aio', ip: [ "#{@ipv4_net1}.10", "#{@ipv4_net2}.10", "#{@ipv4_net3}.10", "#{@ipv4_net4}.10" ])

Vagrant.configure('2') do |config|
  config.vm.define 'aio' do |vm|
    host = 'aio'
    vm.vm.box = platform
    vm.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.volume_cache = 'none'
    end
    vm.vm.synced_folder '.', '/vagrant', type: "rsync"
    @hosts.get(host).ip.each do |ip|
      vm.vm.network :private_network, :ip => ip
    end

    vm.vm.hostname = @hosts.fqdn(host)

    vm.vm.provision 'shell' do |s|
      s.path = common + 'network.sh'
      s.args = [ @ipv4_default_gw, @hosts.to_s ]
    end

    vm.vm.provision 'shell' do |s|
      s.path = common + 'repos/openstack.sh'
      s.args = [ platform, openstack, openstack_version, "#{flea}" ]
    end
#    vm.vm.provision 'shell', path: common + 'certificates.sh'
    vm.vm.provision 'shell' do |s|
      s.path = common + 'opm.sh'
      s.args = [ opm, opm_branch ]
    end
    vm.vm.provision 'shell', path: common + 'selinux_off.sh'
    vm.vm.provision 'shell' do |s|
      s.path = common + 'puppet_no_master.sh'
      s.args = [ '/usr/share/openstack-puppet/modules' ]
    end
    vm.vm.provision 'shell' do |s|
      s.path = common + 'playstack.sh'
      s.args = [ 'master', @hosts.get(host)[0], @hosts.get(host)[1], @hosts.get(host)[2], 'true' ]
    end
  end
end
